### ISSUE TITLE
User name issue inside hydrate method

### ISSUE THREAD

**Issue by BlackBoba** [helpscout/helpscout-api-php#108]
There is comment inside customer class hydrate function:
- "When a customer is supplied via the "createdBy" field it doesn't use the "name" suffix".
The exact same issue appears with the User class. It can be fixed in the same way.

**Comment by bkuhl** [comment]
This is fixed in [v2.1.0](https://github.com/helpscout/helpscout-api-php/releases/tag/2.1.0), thanks for bringing it to our attention!
