### ISSUE TITLE
Conversation withCustomFieldById() filter builds incorrect URL?

### ISSUE THREAD

**Issue by karlbuckland** [helpscout/helpscout-api-php#129]
When filtering a conversation and using ->withCustomFieldById(), the API produces the query string argument &customFieldIds=...

But actually, according to the [docs](https://developer.helpscout.com/mailbox-api/endpoints/conversations/list/#customfieldsbyids) this should be 'customFieldsByIds'?

**Comment by bkuhl** [comment]
Thanks for bringing this up, I've gone ahead and created a PR to adjust it.

**Comment by karlbuckland** [comment]
Great - thank you.

**Comment by bkuhl** [comment]
Resolved with https://github.com/helpscout/helpscout-api-php/releases/tag/2.2.2
