### ISSUE TITLE
'getConversationsForCustomerByMailbox' method ignore 'tag' param

### ISSUE THREAD

**Issue by JakubOnderka** [helpscout/helpscout-api-php#13]
I am trying to get conversations with tag 'LEAD' from mailbox, by this code:
```php
return $this->helpscoutApi->getConversationsForCustomerByMailbox(
    $mailboxId,
    $customer->getId(),
    ['page' => $page, 'tag' => 'LEAD']
);
```
but returned are also conversations with no tag 'LEAD' too.

I think, this is because in getConvoParam method are set accepted params only to 
```php
array('page','fields','status','modifiedSince')
```
but in API definition is also accepted 'tag' param: http://developer.helpscout.net/help-desk-api/conversations/list/

**Comment by stevenwadejr** [comment]
Hi @JakubOnderka, 

This has been fixed with the latest release [1.4.0](https://github.com/helpscout/helpscout-api-php/tree/1.4.0).
