### ISSUE TITLE
Missing customer delete?

### ISSUE THREAD

**Issue by mentalstring** [helpscout/helpscout-api-php#137]
I'm just starting with Mailbox API 2.0 and trying to get my head around it. Unless I'm missing something (quite possible), `$client->customers()->delete($customerId);` is not implemented, despite being on the examples?

**Comment by bkuhl** [comment]
Doh!  Sorry about that, looks like one of those scenarios where we got carried away.  That functionality isn't actually available so I'll submit a PR to remove it from the README.
