### ISSUE TITLE
example/threads.php is broken

### ISSUE THREAD

**Issue by nextend** [helpscout/helpscout-api-php#151]
The threads.php example is broken, located at: https://github.com/helpscout/helpscout-api-php/blob/master/examples/threads.php

`$threads = $client->getThreads($conversationId);`
should be:
`$threads = $client->threads()->list($conversationId);`

Also the getThreads method on a conversation does not work and returns noting:
`$client->conversations()->get(12)->getThreads();`

**Comment by bkuhl** [comment]
Thanks for reporting the issue with invalid syntax in our example.  We updated our syntax prior to initial launch of this version and missed updating that example 😞 

**Also the getThreads method on a conversation does not work and returns noting:**

A conversation's threads are not eagerly loaded and `getThreads()` only loads them when they're already loaded (I've updated the phpdoc on that method to clarify this).  To get the threads using `getThreads()` you need to do this:

```
$conversationRequest = new ConversationRequest();
$conversationRequest->withThreads();
$conversation = $client->conversations()->get(12, $conversationRequest);
```
