### ISSUE TITLE
Missing Attachment data (attachment url) returned in Thread request

### ISSUE THREAD

**Issue by wking-io** [helpscout/helpscout-api-php#154]
The Attachment url was recently added as a response in the _embedded thread response as seen here: https://developer.helpscout.com/mailbox-api/endpoints/conversations/threads/list/#resource-links

We really need this url for our application.

**Comment by bkuhl** [comment]
You're absolutely right, we are missing that.  This is pretty important to get added given our timeline for deprecating v1 of our API so we'll work towards addressing this as soon as possible.

**Comment by wking-io** [comment]
Thank you! I think it was a pretty recent change or at least recent update to the docs so no worries! Thank you for the quick response! :)

Is there anything that can be done to help you get this released?

**Comment by wking-io** [comment]
Thank you! We will test this out this week and let you know!
