### ISSUE TITLE
Error with all threads Customer Hydration

### ISSUE THREAD

**Issue by wking-io** [helpscout/helpscout-api-php#161]
Since the new update where threads fetched using `withThreads` now return the correct Thread Classes. The Thread classes `ReplyThread`, `CustomerThread`, and `ChatThread` all run `hydrateCustomer`: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Conversations/Threads/CustomerThread.php#L32

This throws an error because the `emails` property in the `Customer` Class is set here with a collection of non-extractable email arrays instead of the `Email` Class: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Conversations/Threads/Support/HasCustomer.php#L34

Then since the `Customer` response can be missing the `_embedded['emails']` property the correct way to hydrate the `Email` class is skipped: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Customers/Customer.php#L172

Meaning when the `Customer` Class is extracted it errors out here: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Customers/Customer.php#L223

Because the `$emails` property is a `Collection` of arrays instead of `Email`

**Comment by bkuhl** [comment]
Can you help me reproduce the issue?  Currently I'm doing this and am not experiencing the error:

```
$conversationRequest = (new ConversationRequest())
     ->withCreatedByCustomer()
     ->withThreads();
$conversation = $client->conversations()->get(xxxxxxxxx, $conversationRequest);
var_dump($conversation);
```

I'm showing the `Customer` and their email are hydrated correctly.

**Comment by wking-io** [comment]
we were using `withPrimaryCustomer` I do not know if that effects anything

**Comment by wking-io** [comment]
Also, I am not quite sure how to reproduce it, but the idea would be that you have a `CustomerThread` where the `Customer` does not have any `_embedded['emails']`. So the first time the `setEmails` method is called it is assigned a `Collection` of `Arrays` and when it tries to extract the Customer it fails because it expects the `emails` property to always be a `Collection` of `Emails` because it expects it to be `Extractable` here: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Customers/Customer.php#L223

I think my point was there should never be a time that `setEmails` is called where it is passed anything other than a `Collection` of `Emails` like it is here: https://github.com/helpscout/helpscout-api-php/blob/047bf6b06ef8ae3bdfa93f16f429790035e2d107/src/Conversations/Threads/Support/HasCustomer.php#L34

**Comment by bkuhl** [comment]
Can you reach out to us via support@helpscout.com and supply the conversationId you're using?

**Comment by wking-io** [comment]
Done! :)
