### ISSUE TITLE
Extract method throw an error

### ISSUE THREAD

**Issue by llemurya** [helpscout/helpscout-api-php#166]
Try to call extract method from Collection, but it throws an error **Entity is not extractable**.

My code is:

`$filters = (new ConversationFilters())
        ->withMailbox(29842)
        ->withStatus('all');
    $conversations = $hs->conversations()->list($filters)->extract();`

For the customers, the same code works properly.

`$matches = $hs->customers()->list($filters)->extract();`

I checked the instance of the objects and it is instance of Conversation that implements Extractable interface.

Could you provide an example how to do it properly.

Thanks!

**Comment by bkuhl** [comment]
I believe the error you're encountering was fixed in [v2.3.3](https://github.com/helpscout/helpscout-api-php/releases/tag/2.3.3).  If you still have issues after upgrading to that version feel free to re-open this issue.
