### ISSUE TITLE
"types" seems to have no effect with User\Replies

### ISSUE THREAD

**Issue by jproy418** [helpscout/helpscout-api-php#169]
Hi,

I don't know if it's a bug in the API or in the PHP Wrapper, but when i use the function runReport(User\Replies::class,$params) I get the same values no matter the type I set (email, chat or phone).  
 
**Eg. 1 :** 

$params = [
            'start' => '2019-04-01T00:00:00Z',
            'end' =>  '2019-04-03T23:59:59Z',
            'user' => 305657,
            'types' => 'email',
            'viewBy' => 'day'
        ];

$rapport = $this->client->runReport(User\Replies::class,$params);
   
Array
(
    [current] => Array
        (
            [0] => Array
                (
                    [date] => 2019-04-01T00:00:00Z
                    [replies] => 21
                )

            [1] => Array
                (
                    [date] => 2019-04-02T00:00:00Z
                    [replies] => 18
                )

            [2] => Array
                (
                    [date] => 2019-04-03T00:00:00Z
                    [replies] => 9
                )
        )
)

**Eg. 2 :** 

$params = [
            'start' => '2019-04-01T00:00:00Z',
            'end' =>  '2019-04-03T23:59:59Z',
            'user' => 305657,
            'types' => 'chat',
            'viewBy' => 'day'
        ];

$rapport = $this->client->runReport(User\Replies::class,$params);

Array
(
    [current] => Array
        (
            [0] => Array
                (
                    [date] => 2019-04-01T00:00:00Z
                    [replies] => 21
                )

            [1] => Array
                (
                    [date] => 2019-04-02T00:00:00Z
                    [replies] => 18
                )

            [2] => Array
                (
                    [date] => 2019-04-03T00:00:00Z
                    [replies] => 9
                )
        )
)

Thank you

**Comment by bkuhl** [comment]
Hey, thanks for posting about this.  This definitely looks like an issue because I'm able to reproduce this as well.

@bob983 This looks to me like an issue with the API.  `types` is correctly being populated in the request that is made to the API.  The date range does impact the results, so we know the query string is also being appended:

```
    private $path =>
    string(24) "/v2/reports/user/replies"
    private $query =>
    string(92) "user=93972&start=2019-04-01T00%3A00%3A00Z&end=2019-04-03T23%3A59%3A59Z&types=chat&viewBy=day"

```

**Comment by bob983** [comment]
@bkuhl I'll have a look - I'm in a process of refactoring User Reports anyway, I'll check `types` as well.

**Comment by bob983** [comment]
@bkuhl @jproy418 bad news - I checked with our team and the `types` param is not supported for user replies - it's because only emails can have replies. I will remove the `types` param from the documentation.

**Comment by jproy418** [comment]
Ok, makes sens.  Thanks!
