### ISSUE TITLE
List Team Members

### ISSUE THREAD

**Issue by jproy418** [helpscout/helpscout-api-php#174]
Hi,
Is it possible to use the PHP Client to call the 2 new endpoints (List Teams and List Team Members.) just added to the API ? 

Thank You!

**Comment by bkuhl** [comment]
Hey!  This is something that is on our radar that that we do plan on adding to the SDK I'm just not able to provide an exact timeline at the moment.

**Comment by FutursetudiantsUdeM** [comment]
Yes! That would be greatly appreciated it, as we cannot move away from V1 without this... Thanks @bkuhl !

**Comment by bkuhl** [comment]
This was included in [v2.4.0](https://github.com/helpscout/helpscout-api-php/releases/tag/2.4.0), so you're free to migrate anytime!

**Comment by FutursetudiantsUdeM** [comment]
-- Please reply above this line --


Bonjour Helpscout/helpscout-Api-Php,

 Nous avons bien reçu votre courriel. Soyez assuré que nous ferons
le nécessaire pour vous répondre rapidement. Il faut généralement
allouer un délai de deux à cinq jours ouvrables pour obtenir des
réponses à vos questions. 

 Entre temps, vous pouvez consulter la foire aux questions [1] sur
notre site. Vous y trouverez les réponses aux questions les plus
fréquemment soulevées. 

 Cordialement, 

 Service de l'admission et du recrutement 
  [2]

Links:
------
[1]
https://admission.umontreal.ca/info-conseils/outils-et-astuces/foire-aux-questions/
[2] https://admission.umontreal.ca/

**Comment by FutursetudiantsUdeM** [comment]
Bonjour,
  
L’Université de Montréal souhaiterait connaître votre opinion sur son service à la clientèle. En participant, vous courez la chance de remporter des écouteurs Powerbeats Pro Totally Wireless d’une valeur de 330 $.

Cela vous intéresse? Cliquez sur le lien ci-dessous pour accéder à un sondage qui ne vous prendra pas plus de 5 minutes à compléter.

** Je participe au sondage : https://fr.surveymonkey.com/r/satisfaction-udem-h2020

Université de Montréal  
C. P. 6205, succursale Centre-ville, Montréal, Québec H3C 3T5, Canada

Afficher dans le navigateur : http://envoi.umtl.ca/v/443/f6b53e6e770a3b578b1eb7b7302a11b984dfc10ba22e057f

**Comment by FutursetudiantsUdeM** [comment]
Bonjour,
  
L’Université de Montréal souhaiterait connaître votre opinion sur son service à la clientèle. En participant, vous courez la chance de remporter des écouteurs Powerbeats Pro Totally Wireless d’une valeur de 330 $.

Cela vous intéresse? Cliquez sur le lien ci-dessous pour accéder à un sondage qui ne vous prendra pas plus de 5 minutes à compléter.

** Je participe au sondage : https://fr.surveymonkey.com/r/satisfaction-udem-h2020

Université de Montréal  
C. P. 6205, succursale Centre-ville, Montréal, Québec H3C 3T5, Canada

Afficher dans le navigateur : http://envoi.umtl.ca/v/443/f6b53e6e770a3b57c04cbc6c522332f3fc0a93a6d5a91238
