### ISSUE TITLE
Validation error when creating Conversation when Customer has default photoType

### ISSUE THREAD

**Issue by nwhetsell** [helpscout/helpscout-api-php#190]
I’m trying to create a `Conversation` with a `Customer` whose [`photoType`](https://github.com/helpscout/helpscout-api-php/blob/00e1454543d7753b2ac2ef39408f5b3969358d2b/src/Customers/Customer.php#L416-L419) has the value `'default'`. Catching the `ValidationErrorException` and running

```php
var_dump($exception->getError()->getErrors());
```

shows:

<pre>
array(2) {
  [0]=>
  object(HelpScout\Api\Http\Hal\VndError)#106 (4) {
    ["message":"HelpScout\Api\Http\Hal\VndError":private]=>
    string(102) "<b>must be one of 'gravatar', 'twitter', 'facebook', 'googleprofile', 'googleplus', 'linkedin', 'unknown'</b>"
    ["logRef":"HelpScout\Api\Http\Hal\VndError":private]=>
    NULL
    ["path":"HelpScout\Api\Http\Hal\VndError":private]=>
    string(18) "<b>customer.photoType</b>"
    ["errors":"HelpScout\Api\Http\Hal\VndError":private]=>
    array(0) {
    }
  }
  [1]=>
  object(HelpScout\Api\Http\Hal\VndError)#107 (4) {
    ["message":"HelpScout\Api\Http\Hal\VndError":private]=>
    string(102) "<b>must be one of 'gravatar', 'twitter', 'facebook', 'googleprofile', 'googleplus', 'linkedin', 'unknown'</b>"
    ["logRef":"HelpScout\Api\Http\Hal\VndError":private]=>
    NULL
    ["path":"HelpScout\Api\Http\Hal\VndError":private]=>
    string(29) "threads[0].<b>customer.photoType</b>"
    ["errors":"HelpScout\Api\Http\Hal\VndError":private]=>
    array(0) {
    }
  }
}
</pre>

I didn’t set the `photoType` of this `Customer` (I actually wasn’t even aware that API existed until seeing this error).

Should `'default'` be a valid value of `photoType`? If not, how does one avoid this error?

**Comment by bkuhl** [comment]
Hey!  Thanks for reporting this.  We've had a few other folks mention the same issue.  The underlying issue seems to be that a recent (intended to be transparent) update to our API was describing the photoType as `default` and not `unknown`, so when that customer is re-saved it fails validation.  Our API team applied a fix which should resolve this.  Can you give it another go?

**Comment by nwhetsell** [comment]
This appears to be fixed, thanks!
