### ISSUE TITLE
conversation can belongs to more than one folders, be api return one folder

### ISSUE THREAD

**Issue by wrmond** [helpscout/helpscout-api-php#194]
i am using mailbox api 2.0.

conversation can belongs to more than one folders, be api return only one folder

**Comment by bkuhl** [comment]
The `folderId` returned by the Mailbox API 2.0 is the primary static folder that the conversation is in.  In the below screenshot, this would be Chats, Unassigned, Assigned, etc. but would NOT be "Waiting for..." as those are tied to workflows.  A Conversation can belong to many Workflow folders.

![Screen Shot 2019-09-03 at 2 26 15 PM](https://user-images.githubusercontent.com/524933/64198986-57addf00-ce57-11e9-9319-fe0a25148fa7.png)

**Comment by wrmond** [comment]
ok thanks for answering.
