### ISSUE TITLE
Inconsistent method fluency

### ISSUE THREAD

**Issue by miken32** [helpscout/helpscout-api-php#197]
All the methods defined in the base classes like `Conversation` or `Thread` are fluent, but those brought in via traits are not. For example, `Conversation::setCustomer()` or `Thread::setText()` have no return value. 

It should be a quick and easy fix to make these remaining methods fluent.

**Comment by bkuhl** [comment]
You're right, we aren't consistent in that way.  We'll put this on our radar to improve.  We'd welcome a PR with tests if you're willing to dive into it :)

**Comment by miken32** [comment]
@bkuhl  Re: tests, what did you have in mind? The existing tests would of course continue to pass with non-fluent methods; should I duplicate the current tests, using the newly fluent methods?

**Comment by bkuhl** [comment]
I think just adding assertions that they return an instance of the object would be sufficient.
