### ISSUE TITLE
Exception on getPage() - The link "page" is not templated

### ISSUE THREAD

**Issue by Sebbe909** [helpscout/helpscout-api-php#198]
Hi,

We're recently working with the API client and trying to get specific mailbox/convo pages. However, it seems the getPage() method always returns the RuntimeException **The link "page" is not templated**. Even on other endpoints like customers. The actual page number does exist btw.

```
$this->client = ApiClientFactory::createClient();
$this->client->useClientCredentials($this->platform->api_key, $this->platform->api_secret);

$listConversations = $this->client->conversations()->list($filters, $convoRequest);

$pagedConversations= $listConversations->getPage( 2 ); //throws the exception

dd($pagedConversations);
```

But also
```
$customers = $this->client->customers()->list();

$otherCustomers = $customers->getPage(5); //throws the exception

dd($otherCustomers);
```

For some reason the HalLink.php method isTemplated always(?) returns false.

Could you guys look into this?

**Comment by Sebbe909** [comment]
@bkuhl Sorry to tag you, but I after reading some other issues I see you're quite an expert/contributor. Is this something you know how to fix? We're stuck for now unfortunately because looping over 400 pages instead of jumping to page 400, takes up all rate limiting.

**Comment by bkuhl** [comment]
Not a problem, I'm sorry I wasn't able to jump on this earlier.  What's happening here is the SDK is expecting the URL to come back in a specific format from the API, and it doesn't look like the URL provided for pagination matches what's expected.

@bob983 Can you chime in on this one?  [Our pagination documentation](https://developer.helpscout.com/mailbox-api/overview/pagination/) seems to suggest that `page` should be templated: 

```
        "page": {
            "href": "https://api.helpscout.net/v2/conversations{?page}",
            "templated": true
        }
```

However what I'm actually seeing in the response is:

```
"_links": {
   "first":{"href":"https://api.helpscout.net/v2/conversations/?page=1"},
   "last":{"href":"https://api.helpscout.net/v2/conversations/?page=32"},
   "next":{"href":"https://api.helpscout.net/v2/conversations/?page=2"},
   "page":{"href":"https://api.helpscout.net/v2/conversations/"},
   "self":{"href":"https://api.helpscout.net/v2/conversations/"}},
   "page":{"size":50,"totalElements":1563,"totalPages":32,"number":1}}
```

**Comment by bob983** [comment]
@bkuhl @Sebbe909 oops, yes, this is most likely a bug in the API. I'll have a look.

**Comment by Sebbe909** [comment]
Thats great @bob983 , thanks. Could you let me know if there's a fix?

@bkuhl thank you as well mate, so the fix should come from Helpscout right? Or is this something that can be fixed in the API client?

**Comment by bkuhl** [comment]
I think the right fix in this scenario is to address the bug on the API side and leave the SDK functioning as it is currently.

**Comment by Sebbe909** [comment]
Hi all,

I know it's probably not the bigges issue for you right now, but I was wondering if you guys maybe have an update/fix in sight? We're still stuck for now unfortunately and would love to dev some integrations.

**Comment by bob983** [comment]
It's still on my mind, I'm actually working on it right now but I'm being interrupted all the time with _bigger_ issues or tasks :) But I did not forget.

**Comment by bob983** [comment]
Alright, the change is love, @Sebbe909 could you have a look, please?

**Comment by bkuhl** [comment]
live* :)

**Comment by bob983** [comment]
:smile:

**Comment by Sebbe909** [comment]
Awesome! That seems to be working :) Thanks!

Though, it seems loading conversations (even without pagination) takes up a huuuuge amount of time. On my Laravel Vagrant machine it takes about a few minutes before this code is done:

```
$client = ApiClientFactory::createClient();
$client->useClientCredentials($migrationPlatform->api_key, $migrationPlatform->api_secret);

$filters = (new ConversationFilters())
  ->withStatus('all')
  ->withMailbox(12345)
  ->withSortField('createdAt');

$convoRequest = (new ConversationRequest())
  ->withThreads()
  ->withAssignee()
  ->withCreatedByCustomer()
  ->withPrimaryCustomer();

$conversations = $client->conversations()->list($filters, $convoRequest);
```

I can't remember it was this bad before. I recall it took a few seconds, not over a few minutes. I tried to play around with the ConversationRequest, to see if that made an impact. It didn't really, except when I removed the withThreads method. Then it took 3 seconds, but obviously it didn't have any threads.

Then adding pagination
```
$conversations = $client->conversations()->list($filters, $convoRequest);
$pagedConversations = $conversations->getPage( 3 );
```
seemed to take even longer, which isn't surprising since it probably does 2 request (first page + other page)

Is this expected behaviour? I can't imagine it is. I understand loading the threads and all takes a hit on your database. But that sh*t crayyyy mane.

Tested from multiple machines, with VPN connection etc. Though on a production server it seemed to be running a tiny bit faster. *shrug*

**Comment by bkuhl** [comment]
Hey Sebbe,

A few minutes is _absolutely_ not expected!  I used the code you provided and executed it today on one of my mailboxes and with 50 conversations it took ~12 seconds.  I executed it directly on my local machine, not inside a vm or docker container.  Can you give it another go and see if you see similar delays?

Looking into this, the SDK is not currently utilizing the [conversation eager loading capabilities](https://developer.helpscout.com/mailbox-api/endpoints/conversations/get/) of the API.  It's actually making additional http requests to fetch the threads, assignee, etc. for each conversation.  So if 50 conversations are loaded, that's 50 additional requests for each eagerly loaded entity that's being made.  On top of that, loading page 3 executes all of that all over again.  This is far less than ideal for a lot of reasons. I'll put this on our backlog to visit in the future.

**Comment by Sebbe909** [comment]
@bkuhl Thanks for getting back (and sorry for my later response). So it seems it was a temp. hickup indeed. Testing on my Laravel Homestead VM it now takes about 15 seconds to get 50 convo's with threads indeed. When doing pagination it takes about double that time (34 second).

I found that ordering ASC takes a bigger hit. When ordering ASC and going to page 2, it takes about 48 seconds.

So not super great yet, but I think the production machine will do a little bit better.

I guess changing the SDK to support eager loading would reduce the load on your servers quite a lot indeed. Sorry I'm not the Helpscout SDK pro yet, else I would've contributed to implement that for you ;)

**Comment by bkuhl** [comment]
Hey Sebbe,

I'm glad to hear it was just temporary and not something that requires more troubleshooting.  Back to being productive!  I have brought eager loading up with the team so it's on our radar, though I don't have an ETA on it.  I'll close this out for now since the main issue is resolved.  If you want to Watch this repo you'll be notified of new releases so you can update once eager loading is available.
