### ISSUE TITLE
ID is not returned after creating new conversation

### ISSUE THREAD

**Issue by eima** [helpscout/helpscout-api-php#20]
ID is not set after creating new conversation. Looks like doPost method parse response with mistakes.

**Comment by stevenwadejr** [comment]
Hi @eima, are you on version 1.5.0? Is there anyway you can post the response here?

**Comment by eima** [comment]
It was on your new version, as we use composer and it downloaded it after update. It began 2 days ago.

Conversation was created, just ID was not parsed correctly after return and it was not set back into the conversation object.

Does it work fine for you? If yes, then i will try to simulate response with new version.

-- 

Regards

Eimantas Norkunas
+37068412313
eimantas@mailerlite.com  

mailerlite .com | email newsletters made easy

On 9 Apr 2015 at 16:19:03, Steven Wade (notifications@github.com) wrote:

Hi @eima, are you on version 1.5.0? Is there anyway you can post the response here?

**Comment by stevenwadejr** [comment]
Hi @eima,

I've tested creating a new conversation with version [1.5.0](https://github.com/helpscout/helpscout-api-php/tree/1.5.0).

Here's the example code I used and the response:

```
try {

    $mailbox = new \HelpScout\model\ref\MailboxRef();
    $mailbox->setId(MAILBOX_ID);

    $customer = new \HelpScout\model\ref\CustomerRef();
    $customer->setId(CUSTOMER_ID);
    $customer->setEmail(CUSTOMER_EMAIL);

    $conversation = new \HelpScout\model\Conversation();
    $conversation->setSubject('Testing 1.5.0');
    $conversation->setMailbox($mailbox);
    $conversation->setCustomer($customer);
    $conversation->setType('email');

    $thread = new \HelpScout\model\thread\Customer();
    $thread->setType('customer');
    $thread->setBody('This is a test of creating a new conversation');
    $thread->setStatus('active');

    $createdBy = new \HelpScout\model\ref\PersonRef();
    $createdBy->setId(CUSTOMER_ID);
    $createdBy->setType('customer');
    $thread->setCreatedBy($createdBy);

    $conversation->setThreads(array($thread));
    $conversation->setCreatedBy($createdBy);

    var_dump($conversation->getId());

    $scout->createConversation($conversation);

    var_dump($conversation->getId());

} catch (Exception $e) {
    echo $e->getMessage();
    echo "\n";
    print_r($e->getErrors());
}
```

That outputs:
```
NULL
string(8) "83125986"
```

Where `NULL` is the dump before creating, and the ID does get set. 

I wonder if you didn't catch the 1.4.0 short term release by accident. 1.4.0 was released late last week and unfortunately introduced a bug in parsing the response at times. 

Please update to 1.5.0 and let me know if you're still experiencing the issues.

**Comment by eima** [comment]
Steven, i am cheking logs and it might be that we got 1.4.0.

Thanks.

**Comment by stevenwadejr** [comment]
Ah. Yeah, unfortunately 1.4.0's parsing bug slipped by us. It was meant to be a short lived version, but either way. Sorry about that.
