### ISSUE TITLE
Testing with ApiClient::mock()

### ISSUE THREAD

**Issue by miken32** [helpscout/helpscout-api-php#201]
Your documentation on testing shows a very limited use case (calling the `ApiClient::mock()` function and checking its return type.) I'd like to build some real-life feature tests, and am either completely misunderstanding things (I am new to testing so this is likely) or there's a problem with the API.

So my test is submitting a POST form that creates a ticket. In the controller I'm doing something like this:

    $endpoint = config("app.env") === "testing" ? $client->mock("conversations") : $client->conversations();

    $id = $endpoint->create($c);
    if ($id) {
        $c = $endpoint->get($id);
         return $c->getNumber() ?? null;
    } else {
        return null;
    }

The obvious intention being to use the mocked endpoint during testing. But I get an exception:

>Received Mockery_2_HelpScout_Api_Conversations_ConversationsEndpoint::create(), but no expectations were specified at /blah/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code:910

So is it me or you?

**Comment by bkuhl** [comment]
Hey Michael,

The example for testing is limited, but is mainly intended to demonstrate how `$client->mock()` works, not actually to demonstrate how to use the Mockery library or design code in a testable way.
In this case, it'd require some changes to your controller to make this code testable.  I'd recommend pulling this into another class so you can use [dependency injection](https://medium.com/tech-tajawal/dependency-injection-di-container-in-php-a7e5d309ccc6) to pass a mocked endpoint to the constructor:

```php
class TicketCreator
{
    protected $conversationsEndpoint;

    public function __construct($conversationsEndpoint)
    {
        $this->conversationsEndpoint = $conversationsEndpoint;
    }

    public function create(Conversation $c)
    {
        $id = $this->conversationsEndpoint->create($c);
        if ($id) {
            $c = $this->conversationsEndpoint->get($id);
            return $c->getNumber() ?? null;
        } else {
            return null;
        }
    }
}
```

Testing can be a hard thing to visualize, so [here's a good example](https://www.sitepoint.com/mock-test-dependencies-mockery/#create-the-unit-test) of a test I'd recommend to get you started with unit testing this.  In practice, for your method it'd look something like this:

```php
class TicketCreatorTest extends \PHPUnit_Framework_TestCase 
{
    public function testCreatesConversations() {
        $client = ApiClientFactory::createClient();
        $mockedConversations = $client->mock('conversations');

        $conversationToCreate = Mockery::mock(Conversation::class);

        // Instead of creating the conversation, we'll simulate that creation by telling the client
        // how to respond as it if we actually created it.
        $conversationId = 25; // doesn't matter what this value is
        $mockedConversations->shouldReceive('create')
            ->with($conversationToCreate)
            ->andReturn($conversationId);

        // Since we're mocking the API, we need to educate our new Conversation on which conversation
        // number it is.
        $newlyCreatedConversation =  Mockery::mock(Conversation::class);
        $newlyCreatedConversation->shouldReceive('getNumber')
            ->andReturn($conversationId);

        // We'll mock the api again
        $mockedConversations->shouldReceive('get')
            ->with($conversationId)
            ->andReturn($newlyCreatedConversation);

        $ticketCreator = new TicketCreator($mockedConversations);
        $this->assertEquals(
            $conversationId,
            $ticketCreator->create($conversationToCreate)
        );
    }
}
```

There are ways to do this differently, such as handling the mocking with phpunit and such.  Keep in mind that when you mock something, it doesn't natively know how to respond to anything, you have to tell it what to do.
