### ISSUE TITLE
Get mailbox users

### ISSUE THREAD

**Issue by jproy418** [helpscout/helpscout-api-php#205]
Hi,

Is it possible to retrieve the users for a mailbox like indicate in the [API doc](https://developer.helpscout.com/mailbox-api/endpoints/users/list/) ?

Eg. $users = $client->users()->list('mailbox=123');

Or the opposite, get all maiboxes for a user ? It would be even better.

Thanks!

**Comment by bkuhl** [comment]
Thanks for reaching out.  The latest SDK version doesn't actually support that endpoint, so I apologize about that.  It's relatively simple to add support for with the architecture we have in place so I went ahead and squeezed it in to my schedule today in this PR: https://github.com/helpscout/helpscout-api-php/pull/206.  We'll get this out in a new version once it gets reviewed.

> Or the opposite, get all maiboxes for a user ? It would be even better.

Would you mind sharing more details about your use case?  I'd like to submit this to our API team and the context on how you'd use it would be helpful.

**Comment by jproy418** [comment]
Hi, 
We have developped a tool for our team to log calls and visits in HelpScout. 
We would like our team to be able from our tool to choose the mailbox depending on the type of customer. We have different mailboxes for differrent countries and languages. 

Thanks!

**Comment by bkuhl** [comment]
https://github.com/helpscout/helpscout-api-php/releases/tag/2.5.0 has been tagged, if you update you can now make use of the ability to list users with access to a given mailbox.

I don't have any word yet on the endpoint for listing mailboxes for a user.  I've submitted that request to our API team and we'll update this issue when that feature becomes available.

**Comment by jproy418** [comment]
Thanks a lot!
