### ISSUE TITLE
Upload attachments

### ISSUE THREAD

**Issue by ifpingram** [helpscout/helpscout-api-php#21]
Hi

There is a bug in the uploading of attachments. I have "fixed" it locally (i.e. dirty hack to make it work!), but i'm afraid I've not got time to do a proper fix with PR etc. Here's the relevant code: 

ApiClient.php

lines 448 - 458: The json_decode is already decoded in doPost line 897, so I have pulled it out. Also, needed to change from accessing variables are stdClass and use array access, due to the json_decode as array on line 897.

```php
	/**
	 * @param  \HelpScout\model\Attachment $attachment
	 * @return void
	 */
	public function createAttachment(Attachment $attachment) {
		list(,$body) = $this->doPost('attachments.json', $attachment->toJson(), 201);

		if ($body) {
			$attachment->setHash($body['item']['hash']);
		}
	}
```

lines 904-907 - this is a nasty hack using error suppression. I guess you will need to work out a proper fix, but this will probably need some thought...

```php
		return array(
			$this->getIdFromLocation(@$response->headers['Location']),
			$response->body
		);
```

Hope this helps - even if you don't use the fixes, it alerts you to the issue.

Thanks & regards

Ingram

**Comment by craig-davis** [comment]
Hi @ifpingram - Thanks for catching this and taking the time to point this out to us. We've put a fix for this on the development schedule and we're going to get to it. 

Thanks!

**Comment by ifpingram** [comment]
my pleasure, glad to be of assistance...

**Comment by stevenwadejr** [comment]
HI @ifpingram, thanks so much for pointing this out and posting the fixed code. We've incorporated your fixes and have published a new [1.5.2](https://github.com/helpscout/helpscout-api-php/releases/tag/1.5.2) release.

I hope this helps!

**Comment by offordscott** [comment]
Quick question... is there a max file size limit the api will accept?

**Comment by stevenwadejr** [comment]
@offordscott our developer docs say we support attachments of 10MB or lower, however, that's the *request* size. The attachment data must be a base64 encoded stream which will add some size padding to the payload, this must be taken into account.
