### ISSUE TITLE
Manage receiving both HTTP 100 and 200

### ISSUE THREAD

**Issue by clinchergt** [helpscout/helpscout-api-php#22]
I've been using your client and when updating a conversation, say, setting its status to `spam`, the API replies with both the `100` and `200` status.
`$response` here https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L936 ends up sending the code `100` even though the call was successful.

At first I thought the parameters were being sent in multiple parts, which prompted the server to yell 'Continue', but this line begs to differ: https://github.com/hamstar/curl/blob/master/lib/curl.php#L161

Furthermore, the `$response` object includes something like `100 ContinueHTTP/1.1 200 OK` as it's status message in one of the header variables, can't remember which exactly right now. This just continues to prove that curl is getting both codes as a response, but decides to keep `100`.

This all causes this check to fail: https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L688
and then this call ends in an error since the response's body is empty and this expects an array: https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L720

**Comment by stevenwadejr** [comment]
Hi @clinchergt,

I'm did some testing to try and update a conversation. I changed only the status each time and I'm getting the appropriate `200` response back. Even directly from the [cURL response](https://github.com/hamstar/curl/blob/master/lib/curl.php#L167) in the library, it sends "HTTP/1.1 200 OK". 

I've tried a few different tests and I spoke to our Public API developer to see if it was possible to have both statuses sent back and nothing pops out at us.

Can you give us a code sample that's failing for you and we can look into it further?

**Comment by stevenwadejr** [comment]
Hi @clinchergt,

We had another report of this issue and were finally able to replicate the problem.

We just pushed a fix for this in the [1.6.3](https://github.com/helpscout/helpscout-api-php/releases/tag/1.6.3) release. 

I hope this helps!

**Comment by clinchergt** [comment]
Thanks for the fix!
