### ISSUE TITLE
Error creating attachment

### ISSUE THREAD

**Issue by wietsedecnijf** [helpscout/helpscout-api-php#23]
[Error messages](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/19820/166615/xtSpVl4untXaJuq/meeweb.local.statik.be%20%20ACT%2075%20rfp_id%2010459%20status%20ml_gebruiker%20uri%20nl%20beheersapplicatie%20admin%20dossiers%2010459.png)

Resolved by changing:
```php
public function createAttachment(Attachment $attachment) {
	list(,$body) = $this->doPost('attachments.json', $attachment->toJson(), 201);

	if ($body) {
		$body = json_decode($body);
		$attachment->setHash($body->item->hash);
	}
}
```
to:
```php
public function createAttachment(Attachment $attachment) {
	list(,$body) = $this->doPost('attachments.json', $attachment->toJson(), 201);

	if ($body) {
		$attachment->setHash($body['item']['hash']);
	}
}
```

Am I doing something wrong?

**Comment by stevenwadejr** [comment]
Hi @wietsedecnijf,

You're not doing anything wrong! We updated the curl library a few versions ago and the body is automatically JSON decoded. Unfortunately this line made it through unupdated. We fixed it with version [1.5.2](https://github.com/helpscout/helpscout-api-php/releases/tag/1.5.2) as referenced here #21.
