### ISSUE TITLE
Page Parameter for ConversationFilters

### ISSUE THREAD

**Issue by xqluzxwise** [helpscout/helpscout-api-php#248]
unable to use page parameter in ConversationFilters to list conversation from a specific page.

**Comment by bkuhl** [comment]
Hey Abhishek,

We'll need some more information in order to be able to assist you.  If you could fill out the [issue template](https://github.com/helpscout/helpscout-api-php/blob/master/ISSUE_TEMPLATE.md) for this issue that'd be very helpful.

**Comment by xqluzxwise** [comment]
Hello, sorry for missing out on the details. Here's the description of my issue.

PHP version: 7.2
SDK version: v2

Current behavior

I am trying to list the conversations from a specific page from a mailbox using ConversationFilters. Currently, when I'm running the request, I can only get 25 results from the first page.

Here's my code:

`// GET conversation with the threads
    $conversationRequest = new ConversationRequest();
    $conversationRequest = $conversationRequest->withThreads();

    $filters = (new ConversationFilters())
        ->withMailbox($from_mailboxid)
        ->withSortField('createdAt')
        ->withSortOrder('asc')
        ->withStatus('all');

$from_conversations = $from_client->conversations()->list($filters);`

Expected behavior

I am trying to get all of the conversations of the mailbox or use filters to get conversations from specific page.

Thanks.

**Comment by bkuhl** [comment]
That's no problem, thanks for the additional details.  When fetching results from the API, the results are paginated.  In this context, `$from_conversations` would be page 1 of the results.  There's several functions to help navigate the pages, see how many pages there are, etc.  You can see the [Pagination docs](https://github.com/helpscout/helpscout-api-php#pagination) for details on how to do this.

**Comment by xqluzxwise** [comment]
Yes. Thanks for the information on the pagination docs. It solves mu issue perfectly.

Thank you.
