### ISSUE TITLE
Query results different from UI?

### ISSUE THREAD

**Issue by JonLaliberte** [helpscout/helpscout-api-php#249]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* PHP version: 7.3
* SDK version: 2

**Current behavior**
We are trying to run a query, but for some reason some conversations are being returned that we do not want included.

**Expected behavior** / **Steps to reproduce**

Here is the code:
```				
$ignoreTags = ' AND -tag:whatever AND -tag:whatever else'; // This is built earlier in the code, but this is the format
$filters = (new ConversationFilters())
->inMailbox(99999999)
->inStatus('pending')
->withQuery('-cf99999999999:[NOW TO *] AND modifiedAt:[NOW-180DAYS TO NOW-9DAYS]' . $ignoreTags);
```
If I echo the query string and run it in the HelpScout UI, it works and shows the conversations I expect. But when the code runs, it returns some conversations that shouldn't be returned. Specifically, the tags don't seem to be being negated.

**Comment by bkuhl** [comment]
Hey Jon,

Looking through our logs I can see the request coming in you've made.  Can you give me an example conversation that is included in the results that shouldn't be?

**Comment by JonLaliberte** [comment]
Hey Ben,

Thanks for looking in to this.

Here are a few: 1215455703, 1215037702, 1214701924

I did some more testing just now, which you'll see polluting the logs a bit, but after seeing your reply I had a suspicion I wanted to confirm. I figured maybe the spaces in that second tag were causing problems. It looks like the API is not liking the spaces in one of the tags. In the UI, when you enter in a tag with spaces, it displays it as I showed in my code example above, but it must be quoting those behind the scenes. I tested just now using a quoted string for the tags with spaces and I believe it resolves the issue.

**Comment by bkuhl** [comment]
Yep!  That'll do it.  The docs actually indicate when querying by tags they should be quoted.  I believe this would serve as an alternative to escaping the spaces.

![Screen Shot 2020-07-14 at 1 57 42 PM](https://user-images.githubusercontent.com/524933/87460025-315de180-c5da-11ea-82de-fb4dfba86be3.png)

**Comment by JonLaliberte** [comment]
Sorry about that Ben, embarrassed I didn't catch this earlier. I think I was getting distracted when switching between the frontend docs and the actual query docs and didn't see it there. My bad.

**Comment by bkuhl** [comment]
It happens to all of us Jon, don't worry about it :)
