### ISSUE TITLE
PHP Fatal error:  Class 'Curl' not found in /HelpScout/ApiClient.php on line 37

### ISSUE THREAD

**Issue by sumobi** [helpscout/helpscout-api-php#25]
I'm probably doing something wrong but I'm struggling to get a simple example up and running. I downloaded the library, added an index.php in the `src` folder and pasted the following code from the readme into my PHP file. I keep getting this error:

`PHP Fatal error:  Class 'Curl' not found in /HelpScout/ApiClient.php on line 37`

The code from the readme I used:

```
include 'HelpScout/ApiClient.php';

use HelpScout\ApiClient;

$scout = ApiClient::getInstance();
$scout->setKey('your-api-key-here'); // I have added my key here

$report = $scout->getConversationsReport([
	'start' => '2014-01-01T00:00:00Z',
	'end' => '2014-12-31T23:59:59Z'
]);
```

![screen shot 2015-07-10 at 2 06 10 pm](https://cloud.githubusercontent.com/assets/52581/8610915/e1125da8-270c-11e5-82a4-4e21342c4acc.png)

Even if I just use `$scout = ApiClient::getInstance();` the same fatal error occurs.

I can also make curl requests via command line fine. I'm using PHP 5.5.10 with Mamp Pro (curl is included). 

Can you please provide some guidance on what I'm doing wrong? I had no trouble using an earlier version of this library, but it was ~v1.3.

**Comment by BlueManLine** [comment]
Did you download the Curl library ( https://github.com/shuber/curl ) ?

**Comment by stevenwadejr** [comment]
Hi @sumobi,

We use [Composer](https://getcomposer.org/) to manage dependencies. The PHP API library can be installed via Composer and Composer will install dependencies automatically. If you don't install the library via Composer, you can still use Composer to install and manage dependencies.

Manage dependencies via Composer:

1) Install Composer if you have not already ([OSX/Unix/Linux](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx), or [Windows](https://getcomposer.org/doc/00-intro.md#installation-windows))
2) Via the command line, go into the Help Scout API package directory.
3) Run Composer to [install dependencies](https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies).

Let me know if you have any further questions or troubles getting the package up and running.

I hope this helps!

**Comment by BlueManLine** [comment]
@stevenwadejr sorry, but your composer.json isnt correct

```
sbluma@katowice:~/webs/local.host/tractcom/source/packages/bluemanos/helpscout$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)       
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - helpscout/api 1.6.3 requires shuber/curl dev-master -> no matching package found.
    - helpscout/api 1.6.3 requires shuber/curl dev-master -> no matching package found.
    - Installation request for helpscout/api ~1.6.3 -> satisfiable by helpscout/api[1.6.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
Because `shuber/curl` library doesnt support composer packages, so composer are not able to fetch the external library.

**Comment by stevenwadejr** [comment]
@BlueManLine not sure why you're seeing that error. `shuber/curl` is a valid Composer package and listed on Packagist [here](https://packagist.org/packages/shuber/curl). The package is available on GitHub [here](https://github.com/hamstar/curl).

I just confirmed that Composer installed all dependencies correctly:

```
➜  helpscout-api-php-master 2  composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing shuber/curl (dev-master 6624992)
    Cloning 6624992df201f9fd7262080117385dd09b0ecd2b

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.7.1)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing symfony/stopwatch (v2.7.1)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.7.1)
    Downloading: 100%         

  - Installing symfony/config (v2.7.1)
    Downloading: 100%         

  - Installing symfony/console (v2.7.1)
    Downloading: 100%         

  - Installing symfony/yaml (v2.7.1)
    Downloading: 100%         

  - Installing satooshi/php-coveralls (v0.6.1)
    Loading from cache

  - Installing codeclimate/php-test-reporter (dev-master 418ae78)
    Cloning 418ae782307841ac50fe26daa4cfe04520b0de9c

  - Installing sebastian/version (1.0.6)
    Downloading: 100%         

  - Installing sebastian/global-state (1.0.0)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.0)
    Loading from cache

  - Installing sebastian/exporter (1.2.0)
    Loading from cache

  - Installing sebastian/environment (1.2.2)
    Loading from cache

  - Installing sebastian/diff (1.3.0)
    Loading from cache

  - Installing sebastian/comparator (1.1.1)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Downloading: 100%         

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.4.1)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (2.3.5)
    Downloading: 100%         

  - Installing phpunit/php-timer (1.0.6)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.4.3)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.4.0)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.1.7)
    Downloading: 100%         

  - Installing phpunit/phpunit (4.7.6)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
symfony/console suggests installing symfony/process ()
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
```

**Comment by BlueManLine** [comment]
@stevenwadejr you are god damn right! :)

But still the problem exists and I dont know why. The problem appear when I'm trying to add the helpscout to existing project (which of course use the Composer feature ;)).

I thought that could happen only because of some problems with my project (based on Laravel), but I just tested the `composer require helpscout/api` on completely clean installation of Laravel framework and the above error happen again. Also Symfony2 isnt "compatible" with the helpscout/api... .

Dont know why... .

**Comment by stevenwadejr** [comment]
@BlueManLine sounds like an issue with minimum stability. 

I did a fresh Laravel install and required our library and saw the same issue you did. I followed [this suggested solution](https://laracasts.com/discuss/channels/general-discussion/need-help-with-composer-minimum-stability/replies/17778) and both `helpscout/api` and `shuber/curl` installed properly.

**Comment by BlueManLine** [comment]
That make sense and works! Thank you! :beers: 
Have a nice Friday.

**Comment by stevenwadejr** [comment]
Cheers! :beers:

**Comment by j4ckse7en** [comment]
Hi There,
I've got the same Problem, i installed everthing with composer:
```
php -d allow_url_fopen=On -d disable_functions= ~/bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing shuber/curl (dev-master 6624992)
    Cloning 6624992df201f9fd7262080117385dd09b0ecd2b

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.7.4)
    Loading from cache

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing symfony/stopwatch (v2.7.4)
    Loading from cache

  - Installing symfony/filesystem (v2.7.4)
    Loading from cache

  - Installing symfony/config (v2.7.4)
    Loading from cache

  - Installing symfony/console (v2.7.4)
    Loading from cache

  - Installing symfony/yaml (v2.7.4)
    Loading from cache

  - Installing satooshi/php-coveralls (v0.6.1)
    Loading from cache

  - Installing codeclimate/php-test-reporter (dev-master 85b5de9)
    Cloning 85b5de950678a25f3e85adb6bc26de7f7f231d18

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/global-state (1.0.0)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.1)
    Loading from cache

  - Installing sebastian/exporter (1.2.1)
    Loading from cache

  - Installing sebastian/environment (1.3.2)
    Loading from cache

  - Installing sebastian/diff (1.3.0)
    Loading from cache

  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.5.0)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.7)
    Loading from cache

  - Installing phpunit/php-timer (1.0.7)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.2.3)
    Loading from cache

  - Installing phpunit/phpunit (4.8.9)
    Loading from cache

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
symfony/console suggests installing symfony/process ()
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
```

I created a test file in the src folder:
```
<?php

include 'HelpScout/ApiClient.php';

use HelpScout\ApiClient;

$hs = ApiClient::getInstance();
$hs->setKey('e36bbc4e3d91ebb06797cbe07eecd141bd4cb90b');

$mailboxes = $hs->getMailboxes();

?>
```
And alo gets this error message:
 Fatal error: Class 'Curl' not found in /home/andytld/public_html/api/helpscout-api-php/src/HelpScout/ApiClient.php on line 37

I also deleted anything and reinstalled everything.
shuber/curl seems to be installed correctly.
I tried it on my own computer and also on a webhosting. but i got the same error on both places.

Maybe you have any tipps for me?

**Comment by stevenwadejr** [comment]
Hi @j4ckse7en, you need to make sure the Composer autoload.php file is included, whether it be manually in your script, or by a framework you may be using. 

Try this adding this as the first line of your code: `require_once 'PATH_TO_ROOT/vendors/autoload.php';`

**Comment by j4ckse7en** [comment]
Hi @stevenwadejr 
Thx for your answer.
I changed the script:

```
<?php
require_once '/home/andytld/public_html/api/helpscout-api-php/vendor/autoload.php';
include 'HelpScout/ApiClient.php';

use HelpScout\ApiClient;

$hs = ApiClient::getInstance();
$hs->setKey('9227629411XXXXXX83189002b2a0');

$mailboxes = $hs->getMailboxes();
echo $mailboxes;
?>
```

But i still got the same error: http://www.j4ck.ch/api/helpscout-api-php/src/test.php

Maybe you got some further Ideas?

**Comment by stevenwadejr** [comment]
If everything installed properly via Composer and you've got the autoloader included, you shouldn't be seeing the error. I would suggest referring to the [installation docs](https://github.com/helpscout/helpscout-api-php#installation) and seeing if one of those methods works for you.

**Comment by j4ckse7en** [comment]
Installing it manually without composer worked without problems ¯\_(ツ)_/¯
Thank you for your help.

**Comment by stevenwadejr** [comment]
Glad to hear!

**Comment by travoltron** [comment]
To fix this, just make sure you add the following to your `composer.json`: 
```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

The issue is that the curl package is a dev release, and your composer install is wigging out because of the inherent instability of that. Setting -dev in the install only works for root level installs, not requirements of those packages themselves. 

Hope it helps someone else!
