### ISSUE TITLE
Expected a value greater than 0. Got: 0

### ISSUE THREAD

**Issue by arbind-ladybird** [helpscout/helpscout-api-php#258]
when trying to get next page via $records = $records->getNextPage(); getting error like **  Expected a value greater than 0. Got: 0  
**
Can anyone suggest me why I'm getting this error.

**Comment by shaunmcilroy** [comment]
Thanks for reaching out @arbind-ladybird -- we'll pass along this note to our engineers to investigate and get you a response when our team return from the Thanksgiving break from 11/30 onwards.

**Comment by bkuhl** [comment]
Hey @arbind-ladybird,

`getNextPage()` actually [loads the next page of results](https://github.com/helpscout/helpscout-api-php/blob/master/src/Entity/PagedCollection.php#L79) using data provided by the last request.  It seems like for this error to happen, there must be a scenario where the public API is providing a `0` for the next page value.  Can you share the values of the output of `$records->getTotalPageCount();` and `$records->getPageNumber();` when this error is encountered?

**Comment by arbind-ladybird** [comment]
This is happening because for createdBy you are directly passing *if
(isset($data['createdBy'])){ *$this->hydrateCreatedBy($data['createdBy']);
*}*
but for some users/customer we are getting id having value 0. But there is
a condition in assert that value can't be 0 it should be greater than 0.
As you have putted condition for closed by user like
if (isset($data['closedBy']) && $data['closedBy'] > 0) {
$user = new User();
$user->setId((int) $data['closedBy']);
$this->setClosedBy($user);
}

So to handle this I have modified two file conversation.php and Thread.php
like this
if (isset($data['createdBy']) && $data['createdBy']['id'] > 0) {
             $this->hydrateCreatedBy($data['createdBy']);
         }

**Comment by bkuhl** [comment]
A fix is now available for this scenario in https://github.com/helpscout/helpscout-api-php/releases/tag/3.3.1

**Comment by arbind-ladybird** [comment]
okay
