### ISSUE TITLE
Abandoned library?

### ISSUE THREAD

**Issue by BlueManLine** [helpscout/helpscout-api-php#26]
HelpScout stop support for the library?

1. The API wrapper use old [curl library](https://github.com/shuber/curl)!! Last update made at 2009 :scream:
The most up-to-date curl library right now is [Guzzle](https://github.com/guzzle/guzzle) with PSR-7 support
2. Why HelpScout PHP API doesnt use PSR-2 code standards? :/ https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by stevenwadejr** [comment]
Hi @BlueManLine,

This library is a bit outdated and showing its age isn't it? I assure you we still support it and we're constantly making updates. That being said, we have big plans for a new version of this library that will use modern packages and incorporate modern best practices and standards. Our goal is to launch the new version later this year to coincide with a newly updated and more powerful public API that we're currently concentrating our efforts on. 

Thank you for your feedback and we ask that you hang in there with us! In the meantime, we do still support v1.x of this library and will continue to for some time in the future.

I hope this helps!

**Comment by duellsy** [comment]
Any word on this new version?

**Comment by stevenwadejr** [comment]
@duellsy version 2 of our public API is under active development and due to be released later 2016. v2 of this library will follow.

**Comment by duellsy** [comment]
Thanks @stevenwadejr , will the new package also cater for using the docs API?
Is there a recommended package to use for the docs API in the mean time?

**Comment by stevenwadejr** [comment]
@duellsy there isn't an official library for the Docs API. At this point, the roadmap of the PHP API library v2 isn't set in stone. We'll add Docs into our considerations.
