### ISSUE TITLE
add sort options to ConversationFilter

### ISSUE THREAD

**Issue by amybowers** [helpscout/helpscout-api-php#260]
* PHP version: current
* SDK version:

**Current behavior**
Trying to use the sortField 'waitingSince' or 'customerName' returns an error even though they're allowed by the API.

**Expected behavior**
Should be able to sort by these fields.

**Steps to reproduce**
1. create a filter
`$filters = (new ConversationFilters())->sortField('waitingSince');`

2. try to retrieve conversations using that filter
You will get an error 
> Expected one of: "createdAt", "customerEmail", "mailboxid", "modifiedAt", "number", "score", "status", "subject". Got: "waitingSince"

**Comment by bkuhl** [comment]
Thanks for reporting this, we've just released [v3.3.0](https://github.com/helpscout/helpscout-api-php/releases/tag/3.3.0) with your contribution!
