### ISSUE TITLE
How to get/set Properties

### ISSUE THREAD

**Issue by sanishkamboj** [helpscout/helpscout-api-php#262]
How to retrieve Properties for a customer.

**Comment by bkuhl** [comment]
Hey,

We haven't yet added support for this to the PHP SDK, but it is on our radar and we're tracking requests for this.  I'm not able to provide a timeline on when this will be implemented, but we would welcome a PR that adds all or partial support for properties.  The good news is that the API `GET /v2/customers` endpoint already supports providing the properties in the response, so hydrating the Customer object is the only step left towards fulfilling this.

We'd welcome a PR that adds support for hydrating this data

**Comment by bkuhl** [comment]
Hey @sanishkamboj, I'm excited to tell you that [v3.4.0](https://github.com/helpscout/helpscout-api-php/releases/tag/3.4.0) introduces the ability to access a Customer's properties and their values once you've already got the `Customer`.  Give this a spin and if you encounter any problems please let us know!

**Comment by arwinvdv** [comment]
@bkuhl Great! I think its not yet possible to update the properties with this sdk?

**Comment by bkuhl** [comment]
Not yet, but I've recorded your request for that feature.  We'll update this thread when that functionality is available.

**Comment by arwinvdv** [comment]
Because I need it now I just developed it and created a pull-request: https://github.com/helpscout/helpscout-api-php/pull/274
I don't know if this in the way you would implement it, but for me it works.

**Comment by leewillis77** [comment]
Adding my voice to the group of people that would like the ability to update customer properties through the SDK.

**Comment by leewillis77** [comment]
As a short-term solution, it would be helpful to expose the underlying restClient from the ApiClient class. Would a PR that did that be accepted?

**Comment by careybaird** [comment]
Also adding my +1 for this

**Comment by bkuhl** [comment]
Thanks to @leewillis77 this is now available in [v3.6.2](https://github.com/helpscout/helpscout-api-php/releases/tag/3.6.2)
