### ISSUE TITLE
Unable to fetch all threads for specific conversation if threads are more than 25

### ISSUE THREAD

**Issue by arbind-ladybird** [helpscout/helpscout-api-php#269]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* PHP version: 7.*
* SDK version: 3.*

**Current behavior** when trying to fetch all threads related to a specific conversation, we are getting only 25 threads by using **$conversation->getThreads().** What about next threads if more than 25 threads are associated. 

**Expected behavior** It should return all threads and on github document it should be mentioned

**Steps to reproduce**
1. 
2.
..

**Comment by bkuhl** [comment]
Hey,

Thanks for reaching out.  I apologize about the delayed response but we'll jump right in here!  `$conversation->getThreads()` will only provide the first page of results and only if those threads are eager loaded and is not paginate-able.  If you need to support pagination, I'd suggest using `$conversation->threads()->list($conversation->getid())` as that will provide you a `PagedCollection` and access to be able to easily paginate results.  There's some examples of working with pagination in [this section of the docs](https://github.com/helpscout/helpscout-api-php#pagination).

We're happy to help if you run into any trouble!

**Comment by arbind-ladybird** [comment]
Thanks for your response. I will try the way you suggested.
