### ISSUE TITLE
Getting Saved Replies fields 

### ISSUE THREAD

**Issue by msalamat** [helpscout/helpscout-api-php#275]
Hello there.

Is there a way to export the Saved Replies field in a mailbox's settings? i.e. 

```
https://secure.helpscout.net/settings/saved-replies/123/100
...                                  /saved-replies/123/101
...                                  /saved-replies/123/300
...                                     
(I have so many!)
```

I couldn't find any functions related to it in the SDK, but wanted to double check. If not, would scraping the HTML be what must happen in this case?

Side question: Similarly, I am trying to export a KB (Knowledge Base) for analysis. I see there are the Docs API but might there be an SDK I'm missing similar to this one that's for the Mailbox API?

**Comment by bkuhl** [comment]
Hey,

There's currently no API/SDK support for exporting or interacting with Saved Replies in general.  However, if you'd still like to bulk export these, you can contact our team via https://www.helpscout.com and we'd be happy to assist you with this.

Unfortunately we don't currently offer any SDK to assist in making use of the Docs API.
