### ISSUE TITLE
How to get Conversation by Ticket ID

### ISSUE THREAD

**Issue by revaxarts** [helpscout/helpscout-api-php#28]
It seems the conversation ID != Ticket ID. There's a `number` which contains the ID I'm searching for but how to get that?

I've tried

`$conversation = $api->getConversation($ticketID)`

Is there something like

`$conversation = $api->getTicket($ticketID)`

**Comment by davidstanley01** [comment]
Do you still need help with this question?

**Comment by revaxarts** [comment]
Not really, I've solved it a couple of days later with a workaround. But you can still answer the questions for others maybe

**Comment by bkuhl** [comment]
`$conversationId` is a globally unique id across all of or our customers whereas `$ticketId` is relative to the company.

**SDK v1** 

To search for conversations by ticketId, you'd search Conversations using the `Number` attribute described in https://developer.helpscout.com/help-desk-api/search/conversations/#search-reference.  

**SDK v2** 

In v2 of the SDK, you'd do this by using `ConversationFilters`:

```
$filters = (new ConversationFilters())
    ->withNumber($ticketId);

$conversations = $client->conversations()->list($filters);
```

**Comment by bhavanakmys** [comment]
can anybody say how to get a ticket Id

**Comment by bkuhl** [comment]
@bhavanakmys The best way to do that would be use either `$client->conversations()->get($conversationId)` if you know the exact id of that conversation, or `$client->conversations()->list()` if you'd like to figure out the idea based on a given set of criteria.  There's [more examples in these docs](https://github.com/helpscout/helpscout-api-php#conversations) on how you can use filters to narrow down the list of conversations you get back from the API.
