### ISSUE TITLE
400 Bad Request response

### ISSUE THREAD

**Issue by jonathanbull** [helpscout/helpscout-api-php#284]
* PHP version: 7.4.21
* SDK version: 3.6.2

**Current behavior**

Our application regularly creates conversations in Help Scout using `->conversations()->create($conversation)`.

At 2022-01-24 21:30:02 UTC we received the following response from the API for one of those calls:

```
Client error: `POST https://api.helpscout.net/v2/conversations` resulted in a `400 Bad Request` response: {"logRef":"3bb98347-c884-48ba-bab9-b2a8bc73f3b3#1299214158","message":"Error parsing request body into JSON","_embedded" (truncated...) "
```

Seeing as this PHP client handles the construction of the request, we believe there's either a bug in the library related to producing that JSON, or a bug in the API backend related to parsing that JSON. We contacted your support team who stated that from the logs the JSON looks valid to them, but they asked that we re-create a ticket here as the request was made using the PHP client. They stated you should be able to trace that using the `logRef` (supplied above).

**Expected behavior**

For the client to not construct a request that invokes a JSON parsing error in the API.

**Steps to reproduce**

Re-send the request logged in `logRef` `3bb98347-c884-48ba-bab9-b2a8bc73f3b3#1299214158`, which was created using the latest version of the PHP client. We can't include that request here as it contains confidential customer information.

**Comment by miguelrs** [comment]
Hey @jonathanbull, thanks for bringing this up! 

I've been checking our logs and looks like the JSON data in the body of your request is being cropped at a certain point, resulting in a malformed JSON string. We will try to investigate why this happened and update you as soon as we can.

**Comment by jonathanbull** [comment]
Thanks @miguelrs !

**Comment by jonathanbull** [comment]
We regularly make requests this size and it's the first time we've seen this error, so I think it must have been a one-off issue like you suggest. Happy to chalk this up to a one-off issue – perhaps network related. Thanks for taking a closer look @miguelrs.
