### ISSUE TITLE
Just a question: How do I get the customer ID from her/his email

### ISSUE THREAD

**Issue by utrenkner** [helpscout/helpscout-api-php#285]
I have the customer's email and want to retrieve her/his customer ID.

I can list the customer with
```
$filter = (new CustomerFilters())
        ->withQuery('email:"my@email.test');

    $customers = $client->customers()->list($filter);
```
But how would I query the resulting $customers (of type PagedCollection) so that I can identify the ID? The direct way is not possible because ID is private. But I do not find a suitable getter function...

**Comment by miguelrs** [comment]
Hi @utrenkner!

There is a section in the README file that explains how to deal with [Pagination](https://github.com/helpscout/helpscout-api-php#pagination).

Also, the Customer class has a [getId()](https://github.com/helpscout/helpscout-api-php/blob/658c37ee11246453b11313152ed2f5bbc609973f/src/Customers/Customer.php#L245-L248) method you can use.

So, once you have your `$customers` collection, you just need to do something like:
```
foreach ($customers as $customer) {
    $customerId = $customer->getId();
    // ...
}
```

Hope that helps!
