### ISSUE TITLE
Conversation CustomField text property missing from API

### ISSUE THREAD

**Issue by pchemali** [helpscout/helpscout-api-php#287]
* PHP version: 8.0
* SDK version: 3.6.2

**Current behavior**
text property for Conversations/CustomField.php was never implemented. https://developer.helpscout.com/mailbox-api/endpoints/conversations/get/#custom-fields, example json shows 4 properties returned, however, PHP only returns 3.

JSON Example:
"customFields" : [ {
    "id" : 8,
    "name" : "Account Type",
    "value" : "8518",
    "text" : "Free"
  }
  
  PHP API
  "customFields" : [ {
    "id" : 8,
    "name" : "Account Type",
    "value" : "8518",
  }

**Expected behavior**
return the text property 

**Steps to reproduce**
1. load a customer conversation with custom fields assigned
2. view the result returned
3. confirm no text property

**Solution**
I have already written a PR to fix this: https://github.com/helpscout/helpscout-api-php/pull/286

**Comment by miguelrs** [comment]
Fixed in #286 🚀
