### ISSUE TITLE
Note not attached to existing Conversation

### ISSUE THREAD

**Issue by revaxarts** [helpscout/helpscout-api-php#29]
I'm trying to add a note to an existing converstaion with

```
$note = new \HelpScout\model\thread\Note();
$note->setBody($notetext);
$note->setType('note');
$note->setCreatedBy($userRef);

$conversation->addLineItem($note);
$conversation->setStatus("active");

$conversation->setTags(array("note_added"));

$api->updateConversation($conversation);

```

While the tag "note_added" is applied correctly the note is missing. A simple example would be awesome.

**Comment by davidstanley01** [comment]
Do you still need help with this question?

**Comment by revaxarts** [comment]
Not really, I've solved it a couple of days later with a workaround. But you can still answer the questions for others maybe

**Comment by bkuhl** [comment]
I'll close this out, someone reopen if you have a question about this.
