### ISSUE TITLE
Is it possible to start a conversation with a customer?

### ISSUE THREAD

**Issue by JosephGabito** [helpscout/helpscout-api-php#297]
Hello! We know that we can create a new conversation _as if the customer sent an email to our mailbox_. This is working well, but we're wondering if it is possible to create a new conversation to be sent to the customer making us the conversation starter? 

Something that behaves like the following form:

<img width="1252" alt="Screenshot 2022-11-16 at 9 29 17 PM" src="https://user-images.githubusercontent.com/81974552/202193366-455f6954-9a61-4027-9cea-d7b0272b7e81.png">

Thanks!

**Comment by jchristopher** [comment]
Hi @JosephGabito would you be able to post your solution to this?

**Comment by jchristopher** [comment]
Ah ha! I poked around a bit more and the key is to use `ReplyThread` _not_ `CustomerThread` and then publishing a Reply draft.

Here's an adaptation of the example:

```php
/**
 * Create Conversation: Initiate Conversation with Customer
 */
$customer = new Customer();
$customer->addEmail('my-customer@company.com');

$thread = new \HelpScout\Api\Conversations\Threads\ReplyThread();
$thread->setCustomer($customer);
$thread->setText('Test');

$conversation = new Conversation();
$conversation->setSubject('Testing the PHP SDK v2: Phone Thread');
$conversation->setStatus('active');
$conversation->setType('email');
$conversation->setMailboxId(80261);
$conversation->setCustomer($customer);
$conversation->makeDraft();
$conversation->setThreads(new Collection([
    $thread,
]));
try {
    $conversationId = $client->conversations()->create($conversation);
    $client->conversations()->publishDraft($conversationId);
} catch (\HelpScout\Api\Exception\ValidationErrorException $e) {
    var_dump($e->getError()->getErrors());
}
```

**Comment by JosephGabito** [comment]
@jchristopher, we're directly sending an HTTP request to Helpscout's API, without utilizing the SDK. However, I believe we've arrived at a similar solution.

Here is an example array that gets encoded into a JSON string and then sent to Helpscout's API:

```PHP
$json_body = array(
    'subject'   => $subject,
    'customer'  => array(
        'email' => $email,
    ),
    'mailboxId' => $mailbox,
    'type'      => 'email',
    'status'    => $status,
    'threads'   => array(
         array(
         	'type'     => $type,
		'customer' => array(
			'email' => $email,
		),
		'text'     => $body,
     ),
    ),
);
```

We simply change the `threads[['type']]` to 'reply'. :)

**Comment by jchristopher** [comment]
Thanks so much for taking the time to reply @JosephGabito! Are you still using the SDK to get the `Bearer` token to send your requests? If so do you have a snippet of that? I'm trying to avoid dealing with oAuth if at all possible, but wrestling with how to get the token from the SDK.

**Comment by jchristopher** [comment]
Turns out we can get the `Authorization` header with `$client->getAuthenticator()->getAuthHeader()` 👍
