### ISSUE TITLE
Missing Delete Customer Endpoint

### ISSUE THREAD

**Issue by ryanito** [helpscout/helpscout-api-php#298]
It seems that this endpoint (https://developer.helpscout.com/mailbox-api/endpoints/customers/delete/) is missing from the SDK.

**Comment by miguelrs** [comment]
The `DELETE Customer` endpoint is now available in [version 3.6.4](https://github.com/helpscout/helpscout-api-php/releases/tag/3.6.4). 

Thank you for your work on this! ❤️
