### ISSUE TITLE
Question: How to get a Customer based on a Property 

### ISSUE THREAD

**Issue by PeterOcansey** [helpscout/helpscout-api-php#299]
I added a location (Accra) property to customer and want to list the customers base on this property

```
$filter = (new CustomerFilters())
        ->withQuery('property:"Accra');

$customers = $client->customers()->list($filter);
```

This returns an empty result. is it possible to query customers based on a Property?

**Comment by miguelrs** [comment]
Hey @PeterOcansey! Unfortunately customer properties are not searchable at the moment in the [List Customers](https://developer.helpscout.com/mailbox-api/endpoints/customers/list/#query) endpoint. We're planning to add that functionality in the future, and when we do that, it will be automatically available to be used through this library.
