### ISSUE TITLE
Is there an overview of how to upgrade to 3.0

### ISSUE THREAD

**Issue by helgatheviking** [helpscout/helpscout-api-php#301]
A documentation question, but is there a list of changes in 3.0 and how to update 2.x code to use the 3.0 api?

**Comment by miguelrs** [comment]
Hey! The best place to see that information is the [releases pages](https://github.com/helpscout/helpscout-api-php/releases) in this repo. 

In particular, the changelog for [the 3.0.0 release](https://github.com/helpscout/helpscout-api-php/releases/tag/3.0.0) contains info about all the breaking changes.

If you have any specific question we'll be happy to help with the upgrade!

**Comment by helgatheviking** [comment]
Thank you! at least upon my first inspection, it looks like I am not impacted by the breaking changes. I appear to already be catching the [`AuthenticationException`](https://github.com/kathyisawesome/woo3pdhelpscout/blob/819a1610ea8c6d553011140d0d75390999c02abe/src/Api/Helpscout.php#L175)... presumably because someone on your team wrote that for me years ago. :)

Still need to test obviously (especially around strongly typed parameters) but :crossed_fingers:
