### ISSUE TITLE
Remove dependency on QuickenLoans/uri-template

### ISSUE THREAD

**Issue by dhazelett** [helpscout/helpscout-api-php#303]
QuickenLoans has just made all of their repos private, please remove this depenency asap.

* PHP version: 7, 8
* SDK version: 3

**Current behavior**
cannot install

**Expected behavior**
install

**Steps to reproduce**
1. composer require helpscout/api

**Comment by helgatheviking** [comment]
I was just going to ask about this.... was thinking an issue template is not necessary in the requires and might make more sense as requires-dev, but going private is entirely different

https://github.com/helpscout/helpscout-api-php/blob/master/composer.json#L17

**Comment by bkuhl** [comment]
Looks like making the repsoitory private here might've been accidental and it's now public again, however switching as done in [this pr](https://github.com/helpscout/helpscout-api-php/pull/304) seems like the ideal path forward.

**Comment by bkuhl** [comment]
This has been resolved with [v3.6.5](https://github.com/helpscout/helpscout-api-php/releases/tag/3.6.5)
