### ISSUE TITLE
Example for how to create an attachment

### ISSUE THREAD

**Issue by helgatheviking** [helpscout/helpscout-api-php#305]
* PHP version: 8.0
* SDK version: 3.0x

I found this issue concerning adding attachments to a conversation:
https://github.com/helpscout/helpscout-api-php/issues/47#issuecomment-289723552

But it's a little confusing to me because I can't tell what `$hs->createAttachment($at);` is meant to be, nor can I find `createAttachment()` in the source any more.

**Comment by helgatheviking** [comment]
Oops... update to say I found:
```
$factory = new AttachmentFactory(new Filesystem());
$file = $factory->make(__FILE__);
$thread->setAttachments(new Collection([$file]));
```

in the [threads example](https://github.com/helpscout/helpscout-api-php/blob/master/examples/threads.php#L29-L31). Is this the current way to add attachments?

**Comment by miguelrs** [comment]
@helgatheviking Yes, that's the way to add an attachment to a thread 👍 

Just make sure you replace the `__FILE__` magic constant with the path of the file you want to upload.
