### ISSUE TITLE
How to get the content of a conversation?

### ISSUE THREAD

**Issue by CorentinSUTT** [helpscout/helpscout-api-php#307]
I would like to know how to get the content of a conversation.
Is it possible?
Actually, I am able to get the preview and the subject of the mail but I can't find how to get the content of the mail.
Do you know a way to get it?

Thanks a lot!

**Comment by CorentinSUTT** [comment]
Thanks a lot for your answer!
And how do I get only the latest thread of the conversation?

**Comment by miguelrs** [comment]
@CorentinSUTT

Threads are by default sorted by `createdAt` (from newest to oldest), which means if you want to get the _most recent_ thread, you can just fetch the `Conversation` and get the first item from the list of threads:

```
$request = (new ConversationRequest())->withThreads();
$conversation = $client->conversations()->get($conversationId, $request);
$mostRecent = $conversation->getThreads()[0]
```

If you want to get the _oldest_ thread (the initial email that started the conversation), and you want your solution to work for any number of threads, then you will need to fetch the `Thread`s directly, and then get the last one:

```
$threads = $client->threads()->list($conversationId)->getLastPage();
$oldestThread = end($threads);
```
