### ISSUE TITLE
Missing data in Webhook class

### ISSUE THREAD

**Issue by gldrenthe89** [helpscout/helpscout-api-php#319]
I have a PR ready for you to merge: https://github.com/helpscout/helpscout-api-php/pull/318

There was data mising in the Webhook class. I have added it.

**Comment by miguelrs** [comment]
The PR was merged and released in 3.9.0 ✅ Thanks for taking the time to improve this code ❤️

**Comment by gldrenthe89** [comment]
> The PR was merged and released in 3.9.0 ✅ Thanks for taking the time to improve this code ❤️

Many thanks
