### ISSUE TITLE
[Suggestion] Remove dependency of shuber/curl

### ISSUE THREAD

**Issue by casperbakker** [helpscout/helpscout-api-php#33]
The project shuber/curl is very old and not maintained properly. It does not even have marked 'releases' which is why you use the 'dev-master' version. This is a unsafe way of requiring packages with Composer.

With default Composer settings, it even fails to install: 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for helpscout/api ^1.8 -> satisfiable by helpscout/api[1.8.0].
    - helpscout/api 1.8.0 requires shuber/curl dev-master -> no matching package found.
```

I would recommend not using this package anymore. Or at least, pin it to a specific commit, so a '2.0' release will not break all your API Client installs.

**Comment by bob983** [comment]
Hi @casperbakker I missed this issues, sorry!

**Comment by bob983** [comment]
Oops, sorry, pushed a wrong button.

**Comment by stevenwadejr** [comment]
Version 1 of this library is set to be deprecated as soon as version 2 of our public API and PHP library are released later this year. `shuber/curl` will remain a dependency of this library's version 1 but will be dropped from version 2.
