### ISSUE TITLE
DropdownFieldRef: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by AdamZ** [helpscout/helpscout-api-php#38]
I'm trying to set the value of a custom dropdown field, and I get:

`Fatal Error: Cannot use object of type stdClass as array`
at
`lib/helpscout/api/src/HelpScout/model/ref/customfields/DropdownFieldRef.php:24`

The field objects are taken from a mailbox object using `$mailbox->getCustomFields()`. It looks like `AbstractCustomFieldRef` just places the option data directly into `$this->options` in its constructor, but `DropdownFieldRef::validate()` tries to access it as an array.

**Comment by stevenwadejr** [comment]
@AdamZ this has been fixed and published in the 1.8.1 release.
