### ISSUE TITLE
Error attaching files

### ISSUE THREAD

**Issue by ndev7** [helpscout/helpscout-api-php#47]
Trying to attach files to a  newly created conversation, it works fine with .txt files but any other files produces the error: 

> The request was not formatted correctly 

`$conversation = new \HelpScout\model\Conversation();`
`$conversation->setSubject("Bugs");`
`$conversation->setMailbox($mailbox);`
`$conversation->setCustomer($customer);`
`$conversation->setID(1);`
`$conversation->setType("phone");`

`$thread = new \HelpScout\model\thread\Customer();`
`$thread->setType("customer");`
`$thread->setBody('test');`
`$thread->setStatus("active");`

`$createdBy = new \HelpScout\model\ref\PersonRef();`
`$createdBy->setId(58200219);`
`$createdBy->setType("customer");`
`$thread->setCreatedBy($createdBy);`

`$at = new \HelpScout\model\Attachment();`
`$at->load('image001.jpg');`
`$hs->createAttachment($at);`
`$thread->addAttachment($at);`

`$conversation->setThreads(array($thread));`
`$conversation->setCreatedBy($createdBy);`

**Comment by acdciron59** [comment]
@ndev7 
`
$at = new \HelpScout\model\Attachment();
$at->mimeType('jpeg'); // set the filetype of your attachment object.
$at->load('image001.jpg');
$hs->createAttachment($at);
$thread->addAttachment($at);
`
Or you can refer to: [this](http://developer.helpscout.net/help-desk-api/conversations/create-attachment/l)

**Comment by davidstanley01** [comment]
Closing as it looks like your question has been resolved. Happy to re-open if you need more help, though.
