### ISSUE TITLE
ApiClient: doGet(): no check for curl errors

### ISSUE THREAD

**Issue by levu42** [helpscout/helpscout-api-php#50]
I just tried to call some API functions while the computer running the script had no internet connection and I got a whole lot of error messages like "trying to get property of non-object" and so on.

It seems, that at least in src/HelpScout/ApiClient.php in doGet() $this->curl->get actually returns an object. And then in doPost() the same, it seems, but I didn't test that yet, how this behaves w/o internet connection.

**Comment by davidstanley01** [comment]
do you still need assistance with this issue?

**Comment by davidstanley01** [comment]
Closing due to no response.
