### ISSUE TITLE
Remove minimum-stability dev

### ISSUE THREAD

**Issue by AndreiIgna** [helpscout/helpscout-api-php#56]
Hello,

I started using the HelpScout API in a PHP project and saw that this library sets minimum-stability as dev. Saw the reason too, it includes a really old library for cURL.

A recommendation would be to use another cURL library, which is up-to-date too (the current one has the last commit 8 years ago) and has all features/security included. There's plenty of them that have all of these and follow the Composer recommendations

Setting the **minimum stability** as dev forces other projects to add this option too. Don't really like to do it, as bugs slip more easily in dev releases. Changing this setting works so I'm able to install HelpScout API, but it opens the possibility to other libraries with dev releases to be included, which is not so okay. Cheers

**Comment by tompedals** [comment]
We have recently updated this library to work with V2 of our Help Desk API. The new client has been improved a lot and also doesn't have a minimum-stability of dev. Closing this issue: https://github.com/helpscout/helpscout-api-php/blob/v2/composer.json#L46
