### ISSUE TITLE
getHappinessReport requires user parameter

### ISSUE THREAD

**Issue by leewillis77** [helpscout/helpscout-api-php#58]
I'm attempting to call the `getHappinessReport()` method based on the requirements listed here http://developer.helpscout.net/help-desk-api/reports/happiness/happiness/

However, in doing so I receive the following exception:

```
InvalidArgumentException: The user parameter is required in /www/sites/wc/wp-content/plugins/helpscout-info-widgets/vendor/helpscout/api/src/HelpScout/ApiClient.php:1090
```

As far as I can tell, that report doesn't take, and certainly shouldn't require a user parameter.

**Comment by davidstanley01** [comment]
Closing as it looks like this has been resolved.
