### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kreynen** [helpscout/helpscout-api-php#59]
https://github.com/helpscout/helpscout-api-php/blob/master/composer.json#L7 says MIT, but there isn't a copy of the MIT license in the repo.  The [MIT license](https://en.wikipedia.org/wiki/MIT_License) also states...

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

That's hard to do when you haven't included it in the initial distribution.

**Comment by craig-davis** [comment]
@kreynen Thanks for bringing this to our attention. I've updated the project to include a new `LICENSE` file.
