### ISSUE TITLE
Update to use Mailbox API 2.0?

### ISSUE THREAD

**Issue by jtsternberg** [helpscout/helpscout-api-php#63]
Your docs site says:
> WE'RE UPGRADING OUR API
> On June 6th, 2019, Mailbox API 1.0 will be sunsetted, and at that time any apps using this legacy API will no longer work. Please use [Mailbox API 2.0](https://developer.helpscout.com/mailbox-api) instead.

And this library appears to use v1:
https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/ApiClient.php#L10

Is there a plan to update this library to use v2?

**Comment by davidstanley01** [comment]
v2 client is is active development and is coming soon. Beta version will hopefully be ready in the next 4-6 weeks

**Comment by jtsternberg** [comment]
For those following on this issue, it would be nice if it remained open until v2 is available, at which point closing this would signal we should test/update.

**Comment by davidstanley01** [comment]
Good point @jsternberg. I’ll re-open and will update this issue when v2 beta is ready.

**Comment by davidstanley01** [comment]
Hello! V2 is ready for use... https://github.com/helpscout/helpscout-api-php/releases/tag/2.0.0. To go with that new version, we've also released a package to help with integration in laravel and lumen projects - https://github.com/helpscout/helpscout-api-php-laravel/releases/tag/1.0.0. I'm going to close this issue now.

**Comment by jtsternberg** [comment]
Awesome, thank you for the update!
