### ISSUE TITLE
Unknown thread type [beaconchat]

### ISSUE THREAD

**Issue by polevaultweb** [helpscout/helpscout-api-php#64]
```Fatal error: Uncaught HelpScout\ApiException: Unknown thread type [beaconchat] in /sites/mysite.com/vendor/helpscout/api/src/HelpScout/model/Conversation.php:104```

**Comment by craig-davis** [comment]
Hi @polevaultweb, 

Thanks for bringing this to our attention. We're going to schedule a fix for this. I don't have a timeline to give you at the moment. We'd certainly accept a pull request if you are able. Otherwise, we'll update this issue when we've got a fix ready to release.

**Comment by polevaultweb** [comment]
@craig-davis I can do although I would assume it would require some internal knowledge, unless the beaconchat type should be something like https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/model/thread/Chat.php?

**Comment by craig-davis** [comment]
You're right, it looks like [our documentation](https://developer.helpscout.com/mailbox-api/endpoints/conversations/get/#response-fields) is out of date. I'll chase this down and get this covered. 

If you need a quick patch, I /think/ you can temporarily add a new entry to this lookup array https://github.com/helpscout/helpscout-api-php/blob/master/src/HelpScout/model/Conversation.php#L93 and map a new `beaconchat` type to the array and map it to the `Chat` model class.
