### ISSUE TITLE
Backfill examples for previously implemented work

### ISSUE THREAD

**Issue by davidstanley01** [helpscout/helpscout-api-php#74]
Targets v2...

Need to add examples of endpoint usage to cover all the gaps. The existing examples were added about halfway through development of v2.

**Comment by KaluKhan** [comment]
Hi,
I am getting Error **400 Bad Request** while creating a new conversation.
The JSON is well formatted, but still facing error. If anyone can help me to sort out this error.
API Url: https://api.helpscout.net/v2/conversations
Reference: https://developer.helpscout.com/mailbox-api/endpoints/conversations/create/#request-fields
Here is the response:
`{
"logRef": "a6ee3949-ec16-4b39-92bc-3600adc3f671#178323051",
"message": "Error parsing request body into JSON",
"_embedded": {
"errors": [],
},
"_links": {
"self": {
"href": "http://developer.helpscout.net/mailbox-api/overview/errors#invalid-json"
}
}
}`

**Comment by bkuhl** [comment]
@KaluKhan The problem you're experiencing doesn't relate to this issue.  Can you please open a new issue and provide the code snippet you used to receive this error?

**Comment by bkuhl** [comment]
Some customer examples were added with https://github.com/helpscout/helpscout-api-php/pull/101

**Comment by PavithraCP** [comment]
I'm interested in contributing to Help Scout open source :) Is this issue still up-to-date and expecting contribution?

**Comment by bkuhl** [comment]
@PavithraCP Thank you for expressing interest!  We have backfilled some examples since this issue was created, but since this issue didn't have a list to begin with, we haven't had a clear "this is done" point in mind.  I'll go ahead and close this out and we'll rely on folks asking for help to indicate where more examples are needed.
