### ISSUE TITLE
Can't get conversations by custom field

### ISSUE THREAD

**Issue by miken32** [helpscout/helpscout-api-php#77]
In the v2 code, there appears to be no way to filter conversations based on custom fields, as described in the API: https://developer.helpscout.com/mailbox-api/endpoints/conversations/list/#custom-fields-search

**Comment by davidstanley01** [comment]
Aw, dang. I think you're right. I'll get to work on this next week after the holiday...

**Comment by davidstanley01** [comment]
I ended up with some time and got to work. With so many out next week, we probably won't get this reviewed and/or merged until the week after that. Let me know if you need it sooner...

**Comment by miken32** [comment]
Haha I just noticed a pull request and was thinking to myself "how could I miss that?" then realized it linked to this issue. No hurry, I can modify local code to match and will advise if we run into any problems with the new code.

**Comment by davidstanley01** [comment]
I’ll merge that PR and tag a new version in the morning.

**Comment by davidstanley01** [comment]
Fixed with #78. Closing issue.

**Comment by dacopavlov** [comment]
Hey guys,

Can someone give an example of how to get a conversation by email? I try many things but didn't succeed to get the result.

This is my last try and its not working:
_$filter = (new CustomerFilters())
            ->withQuery('email:test@gmail.com');
$client = self::initHelpscout();
$customer = $client->customers()->list($filter);_
