### ISSUE TITLE
Return IDs when creating new entities

### ISSUE THREAD

**Issue by BlackBoba** [helpscout/helpscout-api-php#88]
Hi, 
Though restClient method createResource gets ID for newly created entity, all 'create' methods within Endpoint child classes return void. It would be nice to return that ID instead, so it could be used immediately.
For example, in order to create new customer, and then new conversation for that him/she, customer needs to be fetched by email query, in order to get his Id needed for creation of conversation.

**Comment by miken32** [comment]
Agreed, just came to post the same request.

**Comment by davidstanley01** [comment]
https://github.com/helpscout/helpscout-api-php/pull/92 addresses this request

**Comment by davidstanley01** [comment]
Closed in #92 and released in v2.0.3 (https://github.com/helpscout/helpscout-api-php/releases/tag/2.0.3)
