### ISSUE TITLE
How to get Conversation by Customer Email in API v2

### ISSUE THREAD

**Issue by dacopavlov** [helpscout/helpscout-api-php#90]
Can anyone provide an example for API v2 of how to get all conversations with a customer when you have just its email?

I have tried many times but it is not working. This was my last try:
$config = [
    'auth' => [
        'type' => 'client_credentials',
        'appId' => 'exampleAppID',
        'appSecret' => 'exampleAppSecret'
    ]
];

$client = ApiClientFactory::createClient($config);
$filter = (new CustomerFilters())
            ->withQuery('email:example@example.com');
$customer = $client->customers()->list($filter);

**Comment by tompedals** [comment]
You should be able to find all conversations with a given email by using a query.

https://developer.helpscout.com/mailbox-api/endpoints/conversations/list/#email

```
query=(email:"john@appleseed.com")
```

In the PHP SDK you can do this using the `ConversationFilters` and the conversations endpoint. Here is an example of using this filter and endpoint: https://github.com/helpscout/helpscout-api-php/blob/v2/examples/conversations.php#L34

In your case the "query" would be something like `(email:"example@example.com")`.

The customers endpoint you referenced will just return the customers and not conversations.

Let me know how you get on with that.

**Comment by dacopavlov** [comment]
Thank you @tompedals. The problem was that the mail I was given like to test with, was the wrong one, so every time I try I was receiving an empty result.

**Comment by dacopavlov** [comment]
Ok, so this is how I had done in SDK v1 and its working accurate:
```
   $customer = $hs->searchCustomersByEmail($customer_email, 1, 'id');
   if(isset($customer->items[0]->id)) {
       $co = $hs->getConversationsForCustomerByMailbox(
           Kohana::config('config.helpscout_cat_mailbox'),
           $customer->items[0]->id,
           $params = array(),
       );
```
And this is how I try to implement the same in SDK v2:
```
       $request = (new ConversationRequest)
           ->withMailbox()
           ->withPrimaryCustomer()
           ->withCreatedByCustomer()
           ->withCreatedByUser()
           ->withClosedBy()
           ->withThreads()
           ->withAssignee();

       $filter = (new ConversationFilters)
           ->withMailbox(Kohana::config('config.helpscout_mailbox'))
           ->withQuery("email:$customer_email")
           ->withSortField('createdAt')
           ->withSortOrder('desc');

       $conversations = $client->conversations()->list($filter, $request);
```

The first one like I said it works fine, but the second one is giving results for some emails, but for some not. 
So what I'm doing wrong? Why the SDK v2 is not giving all results like SDK v1 is?

**Comment by bkuhl** [comment]
This looks correct, so we'll need to investigate further on our end.  It seems like there might be a difference in the v1 and v2 APIs at play.  To investigate the difference in results we could use some more details about what you're searching for and what you're seeing as incorrect (e.g. - conversation XXXX is missing and should be there).  Can you initiate a conversation with us at [help@helpscout.com ](mailto:help@helpscout.com)so we can support you there?  Please include in the conversation:

 * A link to this GitHub issue
 * User that owns the api creds in use
 * The [`Correlation-ID` header](https://developer.helpscout.com/mailbox-api/overview/v1-v2-differences/#error-messages-and-correlation-id) for the request
 * Values being searched for:
   * Mailbox
   * Customer Email

Thanks for re-opening the issue, we'll get to the bottom of it!

**Comment by dacopavlov** [comment]
Hi, 

So thanks to @bkuhl we find out that there is a difference between API v1 and v2 concerning the returning result for conversations. The API v1 is returning all conversations, but API v2 is returning just the active conversations, so if you need all conversations (even "closed" one, like me) you have to specify that in the filters by adding a filter for status "_->withStatus('all')_". 

So in my case, I have to change the code like this:

`$filter = (new ConversationFilters)
            ->withMailbox(Kohana::config('config.helpscout_mailbox'))
            ->withQuery("email:$customer_email")
            **->withStatus('all')**
            ->withSortField('createdAt')
            ->withSortOrder('desc');`

With this, the API is working as I need.

Thank you all and keep with the great work ;)
