### ISSUE TITLE
getUsers() method not present in ApiClient

### ISSUE THREAD

**Issue by scr4bble** [helpscout/helpscout-api-php#93]
From README.md:
```
/** @var PagedCollection $users */
$users = $client->getUsers();
```

There is no getUsers() method in ApiClient, is there?
https://github.com/helpscout/helpscout-api-php/blob/v2/src/ApiClient.php

**Comment by bkuhl** [comment]
Doh!  it looks like we missed updating the paginated section of the readme when we made other changes to the way users are fetched.  I'll put up a PR real quick to address that.  In the meantime, https://github.com/helpscout/helpscout-api-php/tree/v2#users will be your best source for how to fetch users.
